### PR TITLE
development/google-go-lang: Updated for version go1.7

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by willysr** [comment]
Hi @vbatts 
i tested this on my stable VM and it worked fine, but when i tried to build it on my current machine, it failed with these error messages (i have go 1.6.3 installed but i also tried when go is uninstalled and it still failed). I'm wondering if the changes in the toolchain may have caused this problem?

##### Building Go bootstrap tool.
cmd/dist
# _/tmp/SBo/package-google-go-lang/usr/lib/go1.7/go/src/cmd/dist
cannot load DWARF output from $WORK/_/tmp/SBo/package-google-go-lang/usr/lib/go1.7/go/src/cmd/dist/_obj//_cgo_.o: decoding dwarf section info at offset 0x9: underflow

**Comment by vbatts** [comment]
woah. What is so different in -current? that doesn't seem likely.

**Comment by willysr** [comment]
new toolchain?
glibc and gcc

**Comment by willysr** [comment]
@vbatts, @Ponce suggested to use a pre-built Google GO compiler to anticipate changes different GCC-GO implementation from one version to another like in other distributions, such as Gentoo
https://gitweb.gentoo.org/repo/gentoo.git/plain/dev-lang/go/go-1.7.ebuild

**Comment by vbatts** [comment]
ick. but wget'ing the go1.4.3 tar ball should be find right? as long as it
is in the DOWNLOAD ?

**Comment by willysr** [comment]
yes, it should be fine
anyway, it's been merged in my branch. Do you want to leave it like that since it's working in stable or do you want to revise it for current as well?

**Comment by vbatts** [comment]
updated. PTAL

**Comment by vbatts** [comment]
related issue https://github.com/golang/go/issues/11773

**Comment by willysr** [comment]
it didn't build properly in current (32 bit)
http://pastebin.com/pqbuL9iA

**Comment by willysr** [comment]
hi @vbatts after pulling the latest changes in current's binutils, it still failed on 32 bit current
http://pastebin.com/VasAP6HD

**Comment by willysr** [comment]
i pushed the original version without the bootstrap since it worked just fine, so i'm closing this PR.

**Comment by vbatts** [comment]
Oh good

**Comment by willysr** [comment]
well, i just made a minor change to remove the .new extension and doinst.sh
when upgrading, go.csh and go.sh should be overwritten with the new version.

this is the latest version: https://slackbuilds.org/cgit/slackbuilds/commit/?h=willysr&id=f963cbd82ee265e3c30e6f7ccf81df999a0ce756

**Comment by vbatts** [comment]
Yeah. That's good

**Pull request closed without merging**
